services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    image: local/wave-app:8.3
    container_name: wave-app
    working_dir: /var/www/html/src
    volumes:
      - ./:/var/www/html
    environment:
      TZ: Europe/Moscow
      PUID: 1000
      PGID: 1000
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started

  nginx:
    image: nginx:1.25-alpine
    container_name: wave-nginx
    ports:
      - "8000:80"      # http://localhost:8000
    volumes:
      - ./:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: wave-mysql
    command:
      - --default-authentication-plugin=mysql_native_password
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --skip-name-resolve
    environment:
      MYSQL_DATABASE: wave
      MYSQL_USER: wave
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
      TZ: Europe/Moscow
    ports:
      - "33060:3306"          # публикуем на 33060, чтобы исключить конфликт портов
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h 127.0.0.1 -uroot -proot --silent" ]
      interval: 5s
      timeout: 2s
      retries: 20

  redis:
    image: redis:7-alpine
    container_name: wave-redis
    ports:
      - "6379:6379"
    volumes:
      - redisdata:/data

  queue:
    image: local/wave-app:8.3
    container_name: wave-queue
    working_dir: /var/www/html/src
    volumes:
      - ./:/var/www/html
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_started
    command: sh -lc "php artisan queue:work --tries=3 --timeout=120"

  # WebSockets через soketi (Pusher-протокол)
  soketi:
    image: quay.io/soketi/soketi:1.6.0-16-alpine
    container_name: wave-soketi
    environment:
      SOKETI_DEBUG: "1"
      SOKETI_DEFAULT_APP_ID: "wave"
      SOKETI_DEFAULT_APP_KEY: "wavekey"
      SOKETI_DEFAULT_APP_SECRET: "wavesecret"
      SOKETI_METRICS_SERVER_PORT: "9601"
      SOKETI_REDIS_HOST: "redis"
    depends_on:
      - redis
    ports:
      - "6001:6001"
      - "9601:9601"

  node:
    image: node:20-alpine
    container_name: wave-node
    working_dir: /var/www/html/src
    volumes:
      - ./:/var/www/html
    command: sh -lc "npm ci && npm run dev -- --host --port 5173"
    ports:
      - "5173:5173"
    environment:
      - VITE_HOST=127.0.0.1
      - VITE_PORT=5173
    depends_on:
      - app


volumes:
  dbdata:
  redisdata:
